# Generated by Django 6.1 on 2026-08-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('post_office', '0014_alter_email_recipient_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='client_ip_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='notification_email',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='post_office.email'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='submission_key_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='contact_unread_created'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['client_ip_hash', 'created_at'], name='contact_ip_created'),
        ),
    ]
